[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "91yb74cZ7LWcRMsaEz3bEk95hFH6mHnX5cnxe75fZ49M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/utx0/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
